"""devices

Revision ID: 09e2c6ef9a47
Revises: f8789b786b34
Create Date: 2026-09-07 16:14:48.263962
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '09e2c6ef9a47'
down_revision: str | None = 'f8789b786b34'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('serial', sa.String(length=190), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('os', sa.Enum('ANDROID', 'IOS', name='deviceos', native_enum=False), nullable=False),
    sa.Column('model', sa.String(length=190), nullable=True),
    sa.Column('os_version', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('OFFLINE', 'READY', 'BUSY', 'UNAUTHORIZED', 'ERROR', name='devicestatus', native_enum=False), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('proxy_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proxy_id'], ['proxies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', name='uq_device_account'),
    sa.UniqueConstraint('serial', name='uq_device_serial')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devices')
    # ### end Alembic commands ###
