"""initial schema

Revision ID: 79462791e337
Revises: 
Create Date: 2026-08-27 11:49:16.138004
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '79462791e337'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxies',
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.Enum('RESIDENTIAL', 'MOBILE', 'DATACENTER', name='proxykind', native_enum=False), nullable=False),
    sa.Column('scheme', sa.String(length=10), nullable=False),
    sa.Column('host', sa.String(length=190), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=190), nullable=True),
    sa.Column('password_enc', sa.Text(), nullable=True),
    sa.Column('region', sa.String(length=80), nullable=True),
    sa.Column('sticky', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('UNTESTED', 'OK', 'FAILING', 'RETIRED', name='proxystatus', native_enum=False), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_exit_ip', sa.String(length=64), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspaces',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_items',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('title_template', sa.Text(), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('media_ref', sa.String(length=500), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personas',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('voice', sa.Text(), nullable=True),
    sa.Column('interests', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts',
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('REDDIT', 'THREADS', 'X', 'YOUTUBE', 'INSTAGRAM', 'FACEBOOK', 'TIKTOK', name='platform', native_enum=False), nullable=False),
    sa.Column('handle', sa.String(length=190), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'WARMING', 'ACTIVE', 'NEEDS_HUMAN', 'SUSPENDED', 'DEAD', name='accountstatus', native_enum=False), nullable=False),
    sa.Column('secrets_enc', sa.Text(), nullable=True),
    sa.Column('daily_cap', sa.Integer(), nullable=False),
    sa.Column('warmup_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'handle', name='uq_account_platform_handle')
    )
    op.create_table('campaigns',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('content_item_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stagger_window_seconds', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variants',
    sa.Column('content_item_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('media_ref', sa.String(length=500), nullable=True),
    sa.Column('media_variant_ref', sa.String(length=500), nullable=True),
    sa.Column('media_phash', sa.String(length=64), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variants_content_hash'), 'variants', ['content_hash'], unique=False)
    op.create_table('activity_jobs',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('BROWSE_FEED', 'READ_POST', 'REACT', 'WATCH_VIDEO', name='activitykind', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SCHEDULED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'NEEDS_HUMAN', 'SKIPPED', name='jobstatus', native_enum=False), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activity_due', 'activity_jobs', ['status', 'scheduled_at'], unique=False)
    op.create_table('campaign_groups',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('platform', sa.Enum('REDDIT', 'THREADS', 'X', 'YOUTUBE', 'INSTAGRAM', 'FACEBOOK', 'TIKTOK', name='platform', native_enum=False), nullable=False),
    sa.Column('target', sa.JSON(), nullable=False),
    sa.Column('account_ids', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('proxy_id', sa.UUID(), nullable=True),
    sa.Column('engine', sa.Enum('CAMOUFOX', 'PATCHRIGHT', name='browserengine', native_enum=False), nullable=False),
    sa.Column('fingerprint', sa.JSON(), nullable=False),
    sa.Column('os_family', sa.String(length=20), nullable=False),
    sa.Column('locale', sa.String(length=20), nullable=False),
    sa.Column('timezone', sa.String(length=60), nullable=True),
    sa.Column('cookies_enc', sa.Text(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_health_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_alive', sa.Boolean(), nullable=False),
    sa.Column('consecutive_health_failures', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proxy_id'], ['proxies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', name='uq_profile_account')
    )
    op.create_table('post_jobs',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SCHEDULED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'NEEDS_HUMAN', 'SKIPPED', name='jobstatus', native_enum=False), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target', sa.JSON(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['campaign_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_post_job_idem')
    )
    op.create_index('ix_post_job_due', 'post_jobs', ['status', 'scheduled_at'], unique=False)
    op.create_table('session_events',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('CREATED', 'LOGIN', 'HEALTH_OK', 'HEALTH_FAIL', 'CHECKPOINT', 'TAKEOVER', 'COOKIES_SAVED', name='sessioneventkind', native_enum=False), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_session_event_profile', 'session_events', ['profile_id', 'created_at'], unique=False)
    op.create_table('attempts',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('remote_id', sa.String(length=200), nullable=True),
    sa.Column('remote_url', sa.String(length=500), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['post_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('takeover_requests',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', 'ABANDONED', name='takeoverstatus', native_enum=False), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('post_job_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=120), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_job_id'], ['post_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_takeover_open', 'takeover_requests', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_takeover_open', table_name='takeover_requests')
    op.drop_table('takeover_requests')
    op.drop_table('attempts')
    op.drop_index('ix_session_event_profile', table_name='session_events')
    op.drop_table('session_events')
    op.drop_index('ix_post_job_due', table_name='post_jobs')
    op.drop_table('post_jobs')
    op.drop_table('profiles')
    op.drop_table('campaign_groups')
    op.drop_index('ix_activity_due', table_name='activity_jobs')
    op.drop_table('activity_jobs')
    op.drop_index(op.f('ix_variants_content_hash'), table_name='variants')
    op.drop_table('variants')
    op.drop_table('campaigns')
    op.drop_table('accounts')
    op.drop_table('personas')
    op.drop_table('content_items')
    op.drop_table('workspaces')
    op.drop_table('proxies')
    # ### end Alembic commands ###
