"""post slots

Revision ID: 9279fd297a14
Revises: 09e2c6ef9a47
Create Date: 2026-09-07 22:52:32.549955
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '9279fd297a14'
down_revision: str | None = '09e2c6ef9a47'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_slots',
    sa.Column('platform', sa.Enum('REDDIT', 'THREADS', 'X', 'YOUTUBE', 'INSTAGRAM', 'FACEBOOK', 'TIKTOK', name='platform', native_enum=False), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'weekday', 'hour', 'minute', name='uq_post_slot')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_slots')
    # ### end Alembic commands ###
