"""comment seeding, repeats, platform windows, alerts

Revision ID: a5ad0ab8acc2
Revises: b9c6bca6405f
Create Date: 2026-08-27 17:36:43.547909
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'a5ad0ab8acc2'
down_revision: str | None = 'b9c6bca6405f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_windows',
    sa.Column('platform', sa.Enum('REDDIT', 'THREADS', 'X', 'YOUTUBE', 'INSTAGRAM', 'FACEBOOK', 'TIKTOK', name='platform', native_enum=False), nullable=False),
    sa.Column('active_from_hour', sa.Integer(), nullable=False),
    sa.Column('active_to_hour', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', name='uq_platform_window')
    )
    # server_default cho cac hang da co. Autogenerate khong tu them, va thieu no thi
    # ALTER TABLE do vao bang co du lieu se hong voi NotNullViolation.
    op.add_column('campaign_groups', sa.Column('post_kind', sa.Enum('POST', 'COMMENT', name='postkind', native_enum=False), nullable=False, server_default='POST'))
    op.alter_column('campaign_groups', 'post_kind', server_default=None)
    op.add_column('campaigns', sa.Column('repeat', sa.Enum('NONE', 'DAILY', 'WEEKLY', name='repeat', native_enum=False), nullable=False, server_default='NONE'))
    op.alter_column('campaigns', 'repeat', server_default=None)
    op.add_column('campaigns', sa.Column('repeat_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('campaigns', sa.Column('repeat_parent_id', sa.UUID(), nullable=True))
    op.add_column('campaigns', sa.Column('last_repeated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'campaigns', 'campaigns', ['repeat_parent_id'], ['id'], ondelete='SET NULL')
    op.add_column('takeover_requests', sa.Column('alerted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('takeover_requests', 'alerted_at')
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_column('campaigns', 'last_repeated_at')
    op.drop_column('campaigns', 'repeat_parent_id')
    op.drop_column('campaigns', 'repeat_until')
    op.drop_column('campaigns', 'repeat')
    op.drop_column('campaign_groups', 'post_kind')
    op.drop_table('platform_windows')
    # ### end Alembic commands ###
