"""media assets and hashtag sets

Revision ID: b9c6bca6405f
Revises: 79462791e337
Create Date: 2026-08-27 12:23:15.069111
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'b9c6bca6405f'
down_revision: str | None = '79462791e337'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashtag_sets',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('platform', sa.Enum('REDDIT', 'THREADS', 'X', 'YOUTUBE', 'INSTAGRAM', 'FACEBOOK', 'TIKTOK', name='platform', native_enum=False), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_hashtag_set_name')
    )
    op.create_table('media_assets',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('original_name', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.Enum('IMAGE', 'VIDEO', name='mediakind', native_enum=False), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('thumbnail', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_assets')
    op.drop_table('hashtag_sets')
    # ### end Alembic commands ###
