"""relationships, targeted activity, per-weekday windows

Revision ID: f8789b786b34
Revises: a5ad0ab8acc2
Create Date: 2026-09-07 15:06:01.002017
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'f8789b786b34'
down_revision: str | None = 'a5ad0ab8acc2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationships',
    sa.Column('follower_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'DONE', 'FAILED', name='relationstatus', native_enum=False), nullable=False),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'target_id', name='uq_relationship_edge')
    )
    op.create_index('ix_relationship_target', 'relationships', ['target_id', 'status'], unique=False)
    op.add_column('activity_jobs', sa.Column('target_account_id', sa.UUID(), nullable=True))
    op.add_column('activity_jobs', sa.Column('target_url', sa.Text(), nullable=True))
    op.create_foreign_key(
        'fk_activity_target_account',
        'activity_jobs',
        'accounts',
        ['target_account_id'],
        ['id'],
        ondelete='SET NULL',
    )

    # --- platform_windows: mot ban ghi moi ngay thay vi mot ban ghi ca tuan --------
    #
    # Autogenerate viet thang `weekday NOT NULL`, va no hong theo HAI cach khac nhau:
    #
    #   1. ALTER TABLE ADD COLUMN NOT NULL vao bang da co du lieu -> NotNullViolation.
    #   2. Ke ca khi them server_default='0', y nghia cua du lieu cu bi doi am tham:
    #      mot ban ghi cu nghia la "ca tuan", con weekday=0 nghia la "chi thu Hai".
    #      Sau khi nang cap, sau ngay con lai lang le roi ve gio mac dinh ma khong co
    #      dau hieu gi - dung kieu hong ma khong ai phat hien ra.
    #
    # Nen o day nhan ban moi ban ghi cu ra du bay ngay: giu nguyen y nghia cu.
    op.add_column('platform_windows', sa.Column('weekday', sa.Integer(), nullable=True))

    # Bo rang buoc unique cu TRUOC khi chen ban sao - no unique tren rieng `platform`,
    # nen ban sao thu hai se vi pham ngay.
    op.drop_constraint(op.f('uq_platform_window'), 'platform_windows', type_='unique')

    op.execute("UPDATE platform_windows SET weekday = 0 WHERE weekday IS NULL")
    op.execute(
        """
        INSERT INTO platform_windows
            (id, created_at, platform, weekday, active_from_hour, active_to_hour, note)
        SELECT gen_random_uuid(), created_at, platform, d.weekday,
               active_from_hour, active_to_hour, note
        FROM platform_windows
        CROSS JOIN generate_series(1, 6) AS d(weekday)
        WHERE platform_windows.weekday = 0
        """
    )

    op.alter_column('platform_windows', 'weekday', nullable=False)
    op.create_unique_constraint(
        'uq_platform_window_day', 'platform_windows', ['platform', 'weekday']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_platform_window_day', 'platform_windows', type_='unique')
    # Gop bay ngay lai thanh mot: giu ngay thu Hai, bo phan con lai. Co mat mat that
    # neu cac ngay dat khac nhau - nhung schema cu khong the dien ta duoc dieu do.
    op.execute("DELETE FROM platform_windows WHERE weekday <> 0")
    op.create_unique_constraint(
        op.f('uq_platform_window'), 'platform_windows', ['platform']
    )
    op.drop_column('platform_windows', 'weekday')
    op.drop_constraint('fk_activity_target_account', 'activity_jobs', type_='foreignkey')
    op.drop_column('activity_jobs', 'target_url')
    op.drop_column('activity_jobs', 'target_account_id')
    op.drop_index('ix_relationship_target', table_name='relationships')
    op.drop_table('relationships')
    # ### end Alembic commands ###
